stages:
  - test
  - publish
  - deploy

variables:
  DOCKER_DRIVER: overlay2

test:dashboard:
  image: node:carbon-slim
  stage: test
  before_script:
    - cd dashboard
    - npm install
  script:
    - npm run lint
    - npm run test
    - CI=false npm run build

test:server:
  image: python:3.5-slim
  services:
    - mongo
  stage: test
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git
    - pip3 install flake8 pytest pymongo python/
    - pip3 install -r server/requirements.txt
  script:
    - flake8 .
    - MONGO=mongo python3 -m pytest --verbose tests
  artifacts:
    paths:
      - tests/work/server.out
    when: on_failure
    expire_in: 1 week

publish:dashboard:
  image: docker:latest
  stage: publish
  tags:
    - deployment
  only:
    - dev
    - master
  before_script:
    - cd dashboard
  script:
    - docker build -t snailwatch-dashboard-${CI_COMMIT_REF_SLUG} .

publish:server:
  image: docker:latest
  stage: publish
  tags:
    - deployment
  only:
    - dev
    - master
  before_script:
    - cd server
  script:
    - docker build -t snailwatch-server-${CI_COMMIT_REF_SLUG} .

deploy:
  image: deployer
  stage: deploy
  tags:
    - deployment
  only:
    - dev
    - master
  before_script:
    - cd /deploy
  script:
    - ssh -o StrictHostKeyChecking=no -i ./cert root@172.17.0.1 "cd service && ./restart.sh"
