stages:
  - test
  - build
  - push
  - deploy

variables:
  DOCKER_DRIVER: overlay2

test:dashboard:
  image: node:9-slim
  stage: test
  before_script:
    - cd dashboard
    - npm install
  script:
    - npm run lint
    - npm run test
    - CI=false npm run build

test:server:
  image: python:3.5-slim
  services:
    - mongo
  stage: test
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git
    - pip3 install flake8 pytest pymongo client/
    - pip3 install -r server/requirements.txt
  script:
    - flake8 client server tests
    - MONGO=mongo python3 -m pytest --verbose tests
  artifacts:
    paths:
      - tests/work/server.out
    when: on_failure
    expire_in: 1 week

build:dashboard:
  image: docker:latest
  stage: build
  tags:
    - deployment
  only:
    - dev
    - master
  before_script:
    - cd dashboard
  script:
    - docker build -t snailwatch-dashboard-${CI_COMMIT_REF_SLUG} --build-arg PUBLIC_URL=`[ ${CI_COMMIT_REF_SLUG} == 'dev' ] && echo "/dev" || echo "/"` .

build:server:
  image: docker:latest
  stage: build
  tags:
    - deployment
  only:
    - dev
    - master
  before_script:
    - cd server
  script:
    - docker build -t snailwatch-server-${CI_COMMIT_REF_SLUG} .

push:dashboard:
  image: docker:latest
  stage: push
  tags:
    - deployment
  only:
    - master
  script:
    - echo $CI_DOCKERHUB_PW | docker login -u kobzol --password-stdin
    - docker tag snailwatch-dashboard-master kobzol/snailwatch:dashboard
    - docker push kobzol/snailwatch:dashboard

push:server:
  image: docker:latest
  stage: push
  tags:
    - deployment
  only:
    - master
  script:
    - echo $CI_DOCKERHUB_PW | docker login -u kobzol --password-stdin
    - docker tag snailwatch-server-master kobzol/snailwatch:server
    - docker push kobzol/snailwatch:server

deploy:
  image: deployer
  stage: deploy
  tags:
    - deployment
  only:
    - dev
    - master
  before_script:
    - cd /deploy
  script:
    - ssh -o StrictHostKeyChecking=no -i ./cert root@172.17.0.1 "cd service && ./restart.sh"
