stages:
  - test
  - publish
  - deploy

variables:
  DOCKER_DRIVER: overlay2

test:dashboard:
  image: node:carbon-slim
  stage: test
  before_script:
    - cd dashboard
    - npm install
  script:
    - npm run lint
    - npm run test
    - CI=false npm run build

test:server:
  image: python:3.5-slim
  stage: test
  before_script:
    - cd server
    - pip install flake8
  script:
    - flake8 .

publish:dashboard:
  image: docker:latest
  stage: publish
  tags:
    - deployment
  only:
    - dev
    - master
  before_script:
    - cd dashboard
  script:
    - docker build -t snailwatch-dashboard-${CI_COMMIT_REF_SLUG} .

publish:server:
  image: docker:latest
  stage: publish
  tags:
    - deployment
  only:
    - dev
    - master
  before_script:
    - cd server
  script:
    - docker build -t snailwatch-server-${CI_COMMIT_REF_SLUG} .

deploy:
  image: deployer
  stage: deploy
  tags:
    - deployment
  only:
    - dev
    - master
  before_script:
    - cd /deploy
  script:
    - ssh -o StrictHostKeyChecking=no -i ./cert root@172.17.0.1 "cd service && ./restart.sh"
