version: "3"
services:
  server:
    image: kobzol/snailwatch:server
    restart: on-failure
    environment:
      ADMIN_TOKEN: ${ADMIN_TOKEN?You have to specify an admin token}
      MONGO_HOST: mongo
    depends_on:
      - mongo
    ports:
      - ${SERVER_PORT:-5000}:5000
  dashboard:
    image: kobzol/snailwatch:dashboard
    restart: on-failure
    environment:
      API_SERVER: http://localhost:${SERVER_PORT:-5000}
      URL_PREFIX: ${URL_PREFIX:-/}
    depends_on:
      - server
    ports:
      - ${DASHBOARD_PORT:-3000}:3000
  mongo:
    image: mongo:3-jessie
    restart: on-failure
    volumes:
      - ${DB_DIR?You have to specify a database directory}:/data/db
