version: "3"
services:
  server:
    image: kobzol/snailwatch:server
    restart: on-failure
    environment:
      SW_MONGO_HOST: mongo
    depends_on:
      - mongo
    ports:
      - "5000:5000"
  dashboard:
    image: kobzol/snailwatch:dashboard
    restart: on-failure
    environment:
      SW_API_SERVER: http://localhost:5000
    depends_on:
      - server
    ports:
      - "3000:3000"
  mongo:
    image: mongo:3-jessie
    restart: on-failure
    volumes:
     - /home/kobzol/data/snailwatch:/data/db
